// alert("Salom.")
// alert("Sizga qaysi ilova kerak?")
// alert("facebook,twitter,whatsap yoki boshqa ilovani tanlang va o'sha ilovaga kiring,")
// alert("O'sha tanlagan ilovangizga kirmasa,")
// alert(" oldindan uzur so'rab qolamiz.")